[prompt]
sample_steps = 30

negative_prompt = "nude, large breasts, explicit"
height = 768
width = 512
cfg_scale = 6
batch_size = 8

[[prompt.subset]]
prompt = "general, 1girl, solo, long hair, looking at viewer, blue eyes, orange hair, portrait, souryuu asuka langley"
seed = 12345

[[prompt.subset]]
prompt = "sensitive, 1girl, solo, long hair, looking at viewer, blush, smile, simple background, black hair, white background, hair between eyes, jewelry, yellow eyes, horns, necklace, lips, demon girl, demon horns, portrait, slit pupils, albedo (overlord)"
seed = 12345

[[prompt.subset]]
prompt = "general, 1girl, solo, long hair, looking at viewer, blush, smile, blue eyes, long sleeves, ribbon, hair between eyes, closed mouth, school uniform, white hair, ahoge, hair ribbon, sky, day, hand up, cloud, blue sky, red ribbon, eyelashes, window, portrait, close-up"
seed = 12345

[[prompt.subset]]
prompt = "general, sensitive, 1girl, solo, long hair, looking at viewer, blush, smile, simple background, hair ornament, white background, ribbon, closed mouth, bare shoulders, purple eyes, white hair, braid, hair ribbon, flower, pointy ears, hair flower, white flower, x hair ornament, portrait, purple ribbon, crown braid, emilia (re:zero)"
seed = 12345

[[prompt.subset]]
prompt = "sensitive, 1girl, solo, breasts, looking at viewer, blush, dress, closed mouth, cleavage, purple eyes, purple hair, flower, frills, hairband, necktie, blunt bangs, black dress, collar, cosplay, rose, chain, portrait, red flower, black necktie, close-up, lolita fashion, leash, black collar, gothic lolita, bonnet, chain leash, wig, kitagawa marin"
seed = 12345

[[prompt.subset]]
prompt = "general, 1girl, solo, long hair, looking at viewer, smile, closed mouth, twintails, green eyes, white hair, pointy ears, hood, parted bangs, portrait, elf, halloween, halloween costume, ghost costume, frieren"
seed = 12345

[[prompt.subset]]
prompt = "general, 1girl, solo, long hair, blue eyes, simple background, white background, hair between eyes, closed mouth, jewelry, heart, earrings, frills, choker, orange hair, looking to the side, maid, maid headdress, portrait, hand on own face, head rest, hand on own cheek, heart earrings, interface headset, souryuu asuka langley"
seed = 12345

[[prompt.subset]]
prompt = "general, 1girl, solo, long hair, looking at viewer, smile, closed mouth, twintails, green eyes, collarbone, white hair, braid, pointy ears, grey background, twin braids, parted bangs, thick eyebrows, portrait, elf, hair over shoulder, frieren"
seed = 12345

[[prompt.subset]]
prompt = "general, 1girl, solo, black hairband, blindfold, clothing cutout, covered eyes, hairband, mole, mole under mouth, portrait, short hair, white hair, dress, 2b (nier:automata)"
seed = 12345

[[prompt.subset]]
prompt = "general, 1girl, solo, black choker, green eyes, single hair bun, tongue out, hair between eyes, white shirt, portrait, reze (chainsaw man)"
seed = 12345

[[prompt.subset]]
prompt = "general, 1girl, solo, dress, idol, looking at viewer, pink dress, star-shaped pupils, star \\(symbol\\), tongue out, v, hoshino ai \\(oshi no ko\\)"
seed = 12345

[[prompt.subset]]
prompt = "general, 1girl, solo, blue hair, short hair, red eyes, white bodysuit, interface headset, plugsuit, ayanami rei"
seed = 12345

[[prompt.subset]]
prompt = "general, 1girl, solo, animal hat, eyepatch, long hair, blue eyes, red bodysuit, looking at viewer, souryuu asuka langley"
seed = 12345

[[prompt.subset]]
prompt = "general, 1girl, solo, ahoge, brown eyes, hair between eyes, pink hair, v, blue background, white shirt, long hair, oyama mahiro"
seed = 12345

[[prompt.subset]]
prompt = "general, 1girl, solo, blunt bangs, hand on own face, red eyes, red hair, short hair, white background, looking at viewer, red ribbon, school uniform, arima kana"
seed = 12345

[[prompt.subset]]
prompt = "general, 1girl, solo, grey hair, male focus, looking to the side, red background, red eyes, short hair, plugsuit, black bodysuit, nagisa kaworu"
seed = 12345
